apiVersion: cilium.io/v2
kind: CiliumL2AnnouncementPolicy
metadata:
  name: announce-istio-gateway
spec:
  loadBalancerIPs: true

  serviceSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: external-gateway

  interfaces:
    - ens18