apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: announce-istio-gateway
spec:
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: istio-ingress
      io.kubernetes.service.name: external-gateway-istio

  interfaces:
    - ens18