apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-45-10-161-18
spec:
  blocks:
    - start: "45.10.161.18"
      stop:  "45.10.161.18"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: istio-ingress
      io.kubernetes.service.name: external-gateway-istio
