{{- if .Values.cilium.l2announcements.enabled }}
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: external-gateway
spec:
  blocks:
    - start: "45.10.161.18"
      stop: "45.10.161.18"
  serviceSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: external-gateway
{{- end }}
