apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: announce-istio-gateway
spec:
  loadBalancerIPs: true

  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: istio-ingress

  interfaces:
    - ens18