apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shortlink-shop-oms
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: gitops
    argocd.argoproj.io/manifest-generate-paths: ./oms/ops/oms
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shortlink
  destination:
    name: ''
    namespace: shortlink-shop
    server: 'https://kubernetes.default.svc'
  source:
    path: oms/ops/oms
    repoURL: 'https://github.com/shortlink-org/shop'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        shortlink-org/trust-bundle: enabled
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[] | select(.name|test("autogen-."))
