apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spicedb-operator

resources:
  - https://github.com/authzed/spicedb-operator/config?ref=v1.23.0
  - spicedb/secret.yaml
  - spicedb/spiceDBCluster.yaml
  - spicedb/postgres-operator.yaml
  - spicedb/grpcRoute.yaml

images:
  - name: ghcr.io/authzed/spicedb-operator
    newTag: v1.23.0

patches:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: spicedbclusters.authzed.com
    patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: spicedbclusters.authzed.com
        annotations:
          argocd.argoproj.io/sync-options: ServerSideApply=true
  - target:
      version: v1
      kind: Namespace
      name: spicedb-operator
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: spicedb-operator
        annotations:
          argocd.argoproj.io/sync-wave: "-1"
        labels:
          istio-injection: enabled
          kubernetes.io/metadata.name: spicedb-operator
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/enforce-version: latest
