apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oathkeeper
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: gitops
    argocd.argoproj.io/manifest-generate-paths: ./ops/Helm/oathkeeper
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shortlink
  destination:
    name: ''
    namespace: auth
    server: 'https://kubernetes.default.svc'
  source:
    path: ops/Helm/oathkeeper
    repoURL: 'https://github.com/shortlink-org/auth'
    targetRevision: HEAD
    helm:
      releaseName: oathkeeper
      valueFiles:
        - values.yaml
        - secrets+gpg-import-kubernetes://argocd/sops-gpg#sops.asc?jwks.sops.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[] | select(.name|test("autogen-."))
