apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sync-kafka-to-elasticsearch
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: registry.gitlab.com/shortlink-org/gitops/kafka-to-elasticsearch
          resources:
            requests:
              memory: "30Mi"
              cpu: "50m"
            limits:
              memory: "70Mi"
              cpu: "100m"
#          livenessProbe:
#            httpGet:
#              path: /healthz
#          readinessProbe:
#            httpGet:
#              path: /healthz
