x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  aerospikedb:
    <<: *network
    image: aerospike/aerospike-server:8.1.1.1
    restart: on-failure
    container_name: aerospikedb
    init: true
    ports:
      - "3000:3000"
