services:

  coredns:
    profiles:
      - dns
    init: true
    restart: always
    expose:
      - '53/udp'
      - '53/tcp'
    networks:
      simple:
        ipv4_address: 10.5.0.2
    volumes:
