kargo:
    api:
        adminAccount:
            #ENC[AES256_GCM,data:MzPpinWS,iv:+3RPlxP3+ym6AYTUzUlxLCkmRotbXmfMlpMH/1aJTyY=,tag:HBQrDOlA0ZmSEP9h2vsYIw==,type:comment]
            passwordHash: ENC[AES256_GCM,data:HTqpPHtXHFbRCmcC05qhgtQjMMY5IE1OKZlTOGm1B6ccx4wz4oX4ER/JXRCjQeX1CUh/DPOQOf3F4bl2,iv:ny/kBygcxCV1PuoTzm1PZlftBiOIJ7r+fsAUA0rj60g=,tag:AWDWdGwQTQiRJEXPGWHGvw==,type:str]
            tokenSigningKey: ENC[AES256_GCM,data:m/WOHf2mEGg44cR5qAILqqcDSw5xCCzzC4SEmnOiwNuwXMNhm+6i+w==,iv:aHK4KxcrKZiumecLIvb0xScYgRz69ywwUrlHE+NMwhU=,tag:pCTcHDiRsWeXybEhSZ8BvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-17T21:20:28Z"
    mac: ENC[AES256_GCM,data:zTxw1HIPbFrOfEspcPWJzDe9/K0GdfsFNRrrb15hkoaUsZqLcIl9fUu0q19cluJDd0EtmX/XiE0z6V7Yb29z6Xvwog6aEogJoDeQxYbgHFKg5ZouX/Yox+x9bLoHvnqZcBTnKV2qKGWP7njxux8mkpl56ow9RO9yUEAYX1QMUAk=,iv:NWWplrVIwG8qf9UToU4vUcUlVER89YlKb9C2bes4Zmk=,tag:BesYthPRQmRKt1TcDFUFtw==,type:str]
    pgp:
        - created_at: "2025-09-17T21:12:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxDrDE6S/SFjAQv/VkfEGwwRY4AMr6SlVj4tDaijkUbOhL9Y37JXrIv6K9or
            IlFeed4GgkPUVBKV18kbIGzBogSSVl68Yx3WulIdrWNwYnU1ifX6EmF5fcQFAiut
            61KUaNGUn+6GS0jLT1uYtqEfSIRE+rFrOH4xOamMI0AklOC+7KuPtSXyoVRHRSoG
            b6YGVadNskyzA+Lh4eXhAvOETYc8zGMJl/6jgCoAzlCmoGYsEXx7PwNFZrsx/adO
            UjJ/0wKczjid0Ymqc/scjeh7JDO4LlmwhTc2jl1WxAfO17WNk7JZ3Devo9zBI3rM
            bqJoujyMXluo0cp7wzTkiYfZXudr6m5fuCokaPljUJhszs02UWKaWxP6isxHmHKC
            BrliP0tKU9CLVDVIUwW3cwZNMJ7+yV/mmB9wo5etA73+wdquReqSF188c4/uogHZ
            pcyqv+GucnjRhkyJnGD9ijQlVlu574Q9e8X3YkWVLWJeouM6cq3uAEkHZdz3MZ9R
            4UvyX6LpUWPA9L3c83mX1GgBCQIQub7yOq3HztHgaZj1YMprAIKYiItCK2ov9bS7
            6mj3XBtIFbSmCeA5H6QlPw+a8V7CnM/KdM+vGF/KIVEle7NUc1bXjo9pjSukUZXy
            m+CLw3gdbYjhsJTTE4m3M3/ioA8kd4V15g==
            =f5HD
            -----END PGP MESSAGE-----
          fp: C92AE33AF20998F8CA09E819A842078E859DE4F1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
